Repository GEOS-ESM/GEOSadas, pull requests merged in 2021-10, with the labels that each got.

#112 Logic was added to pass the ARCHIVE location from GEOSadas to the Pyr…
  src/Applications/GEOSdas_App/monthly.yyyymm.pl.tmpl
Labels: 0 diff trivial

#113 Update LICENSE to Apache, other license changes
  CONTRIBUTING.md
  COPYRIGHT
  LICENSE
  LICENSE-NOSA
  README.md
Labels: documentation, 0 diff trivial

#120 Properly finalize GEOSgcmPert.x
  src/Applications/GEOSgcmPert_App/GEOSgcmPert.F90
Labels: bug, 0 diff
