Repository GEOS-ESM/GEOSadas, pull requests merged in 2021-12, with the labels that each got.

#139 Feature/msienkie/acft bc cleanup tails
  src/Applications/GEOSdas_App/GEOSdas.csm
  src/Applications/GSI_App/fvssi
Labels: Non 0-diff

#138 Feature/msienkie/#33 implement nrl acqc
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GSI_App/prepobs_prep.bufrtable
  src/Applications/NCEP_Paqc/ChangeLog
  src/Applications/NCEP_Paqc/GMAOprev/gblevents_gmao.f
  src/Applications/NCEP_Paqc/GMAOprev/prevents.f
  src/Applications/NCEP_Paqc/README
  src/Applications/NCEP_Paqc/oiqc/gmao_prepqc
  src/Applications/NCEP_Paqc/prepobs_acarsqc.fd/CMakeLists.txt
  src/Applications/NCEP_Paqc/prepobs_acarsqc.fd/acarsqc.f
  src/Applications/NCEP_Paqc/prepobs_acarsqc.fd/prepobs_acarsqc.merra.parm
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/CMakeLists.txt
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/acftobs_qc.f
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/indexc40.f
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/input_acqc.f
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/output_acqc_noprof.f
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/output_acqc_prof.f
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/pietc.f90
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/pkind.f90
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/pmat.f90
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/pmat2.f90
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/pmat3.f90
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/prepacqc.f
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/prepobs_landc
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/prepobs_prepacqc.gdas.parm
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/prepobs_prepacqc.merra.parm
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/prepobs_waypoints
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/pspl.f90
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/sub2mem_mer.f
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/sub2mem_um.f
  src/Applications/NCEP_Paqc/prepobs_prepacqc.fd/tranQCflags.f
Labels: Non 0-diff

#137 Feature/jstassi/#83/#119/aod parallel and runjob consistency check
  src/Applications/GEOSdas_App/GEOSdas.csm
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/testsuites/C180RPY.input
  src/Applications/GEOSdas_App/testsuites/C180T14RPY.input
  src/Applications/GEOSdas_App/testsuites/C360L181_replay.input
  src/Applications/GEOSdas_App/testsuites/C360L91_replay.input
  src/Applications/GEOSdas_App/testsuites/C48f.input
  src/Applications/GEOSdas_App/testsuites/C90C.input
  src/Applications/GEOSdas_App/testsuites/C90C_ens.input
  src/Applications/GEOSdas_App/testsuites/C90C_replay.input
  src/Applications/GEOSdas_App/testsuites/CMakeLists.txt
  src/Applications/GEOSdas_App/testsuites/checkinput.pl
  src/Applications/GEOSdas_App/testsuites/fpp.input
  src/Applications/GEOSdas_App/testsuites/geos_it.input
  src/Applications/GEOSdas_App/testsuites/prePP.input
  src/Applications/GEOSdas_App/testsuites/runjob.pl
  src/Applications/GEOSdas_App/testsuites/x0046a.input
  src/Applications/GEOSdas_App/testsuites/x0046aRPY.input
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/get_atmens_rst.pl
Labels: 0 diff trivial

#141 Fix uncovered CMake path
  src/Applications/GEOSdas_App/testsuites/CMakeLists.txt
Labels: 0 diff

#142 ADAS Gatekeepers should be notified of all changes
  .github/CODEOWNERS
Labels: 0 diff trivial

#143 fix in gsi CMakefile - from Matt
  components.yaml
Labels: bug, 0 diff

#144 Feature/rtodling/nodeflg fix
  src/Applications/GEOSdas_App/Create_anasa_script.pm
  src/Applications/GEOSdas_App/Create_asens_script.pm
  src/Applications/GEOSdas_App/Create_fsens_script.pm
Labels: bug, 0 diff trivial

#146 minor
  src/Applications/GEOSdas_App/fvsetup
Labels: enhancement, 0 diff trivial

#133 Add checking for prior calculation of virtual temperture before running 'prevents'
  src/Applications/NCEP_Paqc/GMAOprev/CMakeLists.txt
  src/Applications/NCEP_Paqc/GMAOprev/check_virtmp.f
  src/Applications/NCEP_Paqc/oiqc/gmao_prepqc
Labels: bug, Non 0-diff

#147 (1) add ldas anal increments to fcst script
  src/Applications/GEOSdas_App/fvsetup
Labels: 0 diff trivial, bug fix

#148 all in support of GEOS-IT; update to Henry-s Law will cause non-zero …
  components.yaml
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/testsuites/C180RPY.input
  src/Applications/GEOSdas_App/testsuites/C180T14RPY.input
  src/Applications/GEOSdas_App/testsuites/C360L181_replay.input
  src/Applications/GEOSdas_App/testsuites/C360L91_replay.input
  src/Applications/GEOSdas_App/testsuites/C48f.input
  src/Applications/GEOSdas_App/testsuites/C90C.input
  src/Applications/GEOSdas_App/testsuites/C90C_ens.input
  src/Applications/GEOSdas_App/testsuites/C90C_replay.input
  src/Applications/GEOSdas_App/testsuites/fpp.input
  src/Applications/GEOSdas_App/testsuites/geos_it.input
  src/Applications/GEOSdas_App/testsuites/prePP.input
  src/Applications/GEOSdas_App/testsuites/x0046a.input
  src/Applications/GEOSdas_App/testsuites/x0046aRPY.input
  src/Applications/GEOSdas_App/testsuites/x0046a_Summer.input
  src/Applications/GEOSdas_App/write_FVDAS_Run_Config.pl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/setup_atmens.pl
Labels: enhancement, Non 0-diff

#149 revise obs sys for GEOS-IT and proper GOCART/emissions
  components.yaml
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/testsuites/geos_it.input
Labels: enhancement, 0 diff

#150 update GSI for GEOS-IT config; minor script adjustments merging 5.27.…
  components.yaml
  src/Applications/GEOSdas_App/GEOSdas.csm
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/gen_silo_arc.pl
  src/Applications/GEOSdas_App/monthly.yyyymm.pl.tmpl
  src/Applications/GEOSdas_App/monthly_setup.pl
Labels: enhancement, 0 diff
