Repository GEOS-ESM/GEOSadas, pull requests merged in 2022-05, with the labels that each got.

#176 adds updates to handle GEOS-IT and GEOS-R21C system configurations
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/gen_lnbcs.pl
  src/Applications/GEOSdas_App/write_FVDAS_Run_Config.pl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/CMakeLists.txt
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/atmos_enkf.nml.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/obs1gsi_mean.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/obs1gsi_member.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/setup_atmens.pl
Labels: enhancement, 0 diff structural

#178 The script was modified to add an hourtype value for the traj_lcv_rst…
  src/Applications/GEOSdas_App/write_monthly_rc_arc.pl
Labels: 0 diff structural, bug fix

#175 Update the readme file with a note about the 'generic' configuration
  src/Applications/NCEP_Etc/NCEP_bias/init_coeffs.f90
  src/Applications/NCEP_Etc/NCEP_bias/readme_init_coeffs.txt
Labels: documentation, 0 diff

#181 Updates for GEOS-IT: still not final
  components.yaml
  src/Applications/GEOSdas_App/testsuites/geos_it.input
  src/Applications/GEOSdas_App/write_monthly_rc_arc.pl
Labels: enhancement, 0 diff
