Repository GEOS-ESM/GEOSadas, pull requests merged in 2022-08, with the labels that each got.

#194 More for GEOS-IT
  components.yaml
  src/Applications/GAAS_App/ana.rc.tmpl
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/testsuites/geos_it.input
Labels: enhancement, 0 diff

#196 updates to fix aerosol assimilation of AVHRR data for GEOSIT/R21C
  src/Applications/GAAS_App/ana.rc.tmpl
  src/Applications/GEOSdas_App/GEOSdas.csm
Labels: 0 diff trivial

#199 Feature/jstassi/#198/local acquire gaas obs
  src/Applications/GEOSdas_App/GEOSdas.csm
  src/Applications/GEOSdas_App/fvsetup
Labels: enhancement, 0 diff structural

#201 Feature/rtodling/geosit 15aug2022
  components.yaml
  src/Applications/GEOSdas_App/GEOSdas.csm
  src/Applications/GEOSdas_App/fvsetup
Labels: 0 diff trivial

#203 Add fixes to pre-2000 gocart emissions and fvsetup + fix to SBUV n19…
  src/Applications/GEOSdas_App/fvsetup
Labels: 0 diff trivial
