Repository GEOS-ESM/GEOSadas, pull requests merged in 2022-09, with the labels that each got.

#207 Second round of fixes to GEOSIT resource files
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/write_FVDAS_Run_Config.pl
Labels: 0 diff, 0 diff trivial

#206 Feature/karpob/omplp g rename
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/obs1gsi_mean.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/obs1gsi_member.rc
Labels: 0 diff trivial

#209 Orbit params and others
  components.yaml
  src/Applications/GEOSdas_App/GEOSdas.csm
  src/Applications/GEOSdas_App/edhist.pl
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/gen_silo_arc.pl
  src/Applications/GEOSdas_App/write_monthly_rc_arc.pl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmens_arch.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmos_egsi.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/AGCM.rc.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/AtmEnsConfig.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/HISTAENS.rc.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/HISTAGEPS.rc.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/HISTAOSE.rc.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/atmens_storage.arc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/obs1gsi_mean.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/obs1gsi_member.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/obsvr_ensemble.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/setup_atmens.pl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/update_ens.csh
Labels: enhancement, Non 0-diff

#211 add geosit_prep_bufr
  src/Applications/GEOSdas_App/testsuites/geos_it.input
Labels: Non 0-diff, bug fix

#213 version numbers now to all repos
  components.yaml
Labels: 0 diff, 0 diff structural
