Repository GEOS-ESM/GEOSadas, pull requests merged in 2022-02, with the labels that each got.

#152 Update for FPP (5.29.4)
  components.yaml
  src/Applications/GEOSdas_App/edhist.pl
  src/Applications/GEOSdas_App/fvsetup
Labels: Non 0-diff, bug fix

#154 minor fix to mapl; increase arrays size handling acft bias correction
  components.yaml
Labels: 0 diff, 0 diff structural, 0 diff trivial

#156 bug fix in ens setup; sync of HISTORY w/ what FP uses
  components.yaml
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/setup_atmens.pl
Labels: 0 diff, 0 diff structural, 0 diff trivial

#157 fix for TSKINI (surf export) and MAPL file specs
  components.yaml
Labels: 0 diff, 0 diff structural, bug fix

#155 GitHub Actions for MAPLv3 development
  .github/PULL_REQUEST_TEMPLATE/auto_pr_to_mapl3.md
  .github/workflows/push-to-develop.yml
Labels: 0 diff trivial

#159 TKSINICE, GEOSIT history, ManipulateTime fixes
  components.yaml
Labels: 0 diff trivial
