Repository GEOS-ESM/GEOSadas, pull requests merged in 2024-03, with the labels that each got.

#270 Patch for FP: updates for p4 of 5.29.5
  components.yaml
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/obs1gsi_mean.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/obs1gsi_member.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/setup_atmens.pl
Labels: enhancement, Non 0-diff

#271 FP patch:OMPS-LP & GOES-18
  components.yaml
Labels: enhancement, Non 0-diff

#268 R21C DAS Candidate
  components.yaml
  src/Applications/GEOSdas_App/GEOSdas.csm
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/gen_lnbcs.pl
  src/Applications/GEOSdas_App/write_FVDAS_Run_Config.pl
  src/Applications/MKIAU_App/mp_stats.F90
  src/Applications/NCEP_Etc/NCEP_enkf/innovstats.f90
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atm_ens.j
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmens_arch.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmens_stats.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/CMakeLists.txt
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/AtmEnsConfig.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/CAP.rc.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/HISTAENS.rc.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/atmens_storage.arc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/atmos_enkf.nml.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/mp_stats_NP.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/mp_stats_NZ.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/obs1gsi_mean.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/obs1gsi_member.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/post_egcm.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/setup_atmens.pl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/update_ens.csh
  src/Applications/NCEP_Paqc/GMAOprev/gblevents_gmao.f
  src/Applications/NCEP_Paqc/GMAOprev/prevents.f
  src/Applications/NCEP_Paqc/oiqc/oiqcbufr.f
  src/Applications/NCEP_Paqc/prepobs_cqcbufr.fd/cqcbufr.f
  src/Applications/NCEP_Paqc/radcor/m_RadBufr.f
Labels: Non 0-diff

#272 allow overwrite of model output
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/HISTAENS.rc.tmpl
Labels: 0 diff
