Repository GEOS-ESM/GEOSadas, pull requests merged in 2024-11, with the labels that each got.

#296 R21C: Revise distribution: add slurm-array; rev stats
  components.yaml
  src/Applications/GEOSdas_App/testsuites/m21c_j98.input
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atm_ens.j
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atm_ose.j
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmens_efsens.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmens_ntasks.pl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmens_recenter.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmens_stats.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmens_vtrack.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmos_eaod.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmos_egsi.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmos_enkf.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmos_ens2gcm.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/AtmEnsConfig.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/AtmOSEConfig.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/CAP.rc.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/CMakeLists.txt
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/AtmEnsConfig.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/CAP.rc.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/HISTAENS.rc.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/mp_stats_NP.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/mp_stats_NZ.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/post_egcm.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/R21C/post_egcm_diag.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/mp_stats.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/post_egcm.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/post_egcm_diag.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/gcm_ensemble.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/gen_ensbkg.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/gen_ensrst.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/jobgen.pl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/obsvr_ensemble.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/obsvr_ensfinal.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/post_eana.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/post_efso.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/post_egcm.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/setobsvr.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/setperts.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/setup_atmens.pl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/ut_atmens_stats.j
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/ut_rec_stats.j
Labels: enhancement, 0 diff, bug fix

#297 Fix up ADAS CI
  .circleci/config.yml
  components.yaml
Labels: 0 diff

#259 Skip pob=0.0 in ACARS height fix
  src/Applications/NCEP_Paqc/GMAOprev/gblevents_gmao.f
Labels: 0 diff

#303 Feature/rtodling/ompslp n minor ens diag rev
  components.yaml
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/testsuites/x0050RPY_summer.input
  src/Applications/GEOSdas_App/testsuites/x0050_summer.input
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/AtmEnsConfig.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/HISTAENS.rc.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/atmens_storage.arc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/mp_stats.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/post_egcm.rc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/post_egcm_diag.rc
Labels: enhancement, Non 0-diff

#305 Add missing changes for GMI
  components.yaml
Labels: Non 0-diff, bug fix

#306 Python3 fix
  src/Applications/GAAS_App/aeronet_all.py
  src/Applications/GAAS_App/aod_data.py
  src/Applications/GAAS_App/avhrr_all.py
  src/Applications/GAAS_App/avhrr_l2a.py
  src/Applications/GAAS_App/avhrr_nnr.py
  src/Applications/GAAS_App/misr_land.py
  src/Applications/GAAS_App/modis_l2a.py
  src/Applications/GAAS_App/mxd04_l2a.py
  src/Applications/GAAS_App/mxd04_nnr.py
  src/Applications/GAAS_App/patmosx_l2a.py
Labels: 0 diff

#308 Update GMAO_Shared version
  components.yaml
Labels: enhancement, 0 diff

#313 R21C: Additional change related to python3 stuff
  components.yaml
Labels: Non 0-diff
