Repository GEOS-ESM/GEOSadas, pull requests merged in 2025-05, with the labels that each got.

#353 Add cycling JEDI capability to GEOS
  components.yaml
  src/Applications/GEOSdas_App/CMakeLists.txt
  src/Applications/GEOSdas_App/GEOSdas.csm
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/gen_silo_arc.pl
  src/Applications/GEOSdas_App/jedi/CMakeLists.txt
  src/Applications/GEOSdas_App/jedi/cmd_jediset.test
  src/Applications/GEOSdas_App/jedi/etc/CMakeLists.txt
  src/Applications/GEOSdas_App/jedi/etc/JEDIanaConfig.csh
  src/Applications/GEOSdas_App/jedi/etc/SWELLConfig.csh
  src/Applications/GEOSdas_App/jedi/etc/convertinc_geos.yaml
  src/Applications/GEOSdas_App/jedi/etc/geos_3dfgat.yaml
  src/Applications/GEOSdas_App/jedi/etc/geos_3dvar.yaml
  src/Applications/GEOSdas_App/jedi/etc/geos_hyb4denvar.yaml
  src/Applications/GEOSdas_App/jedi/etc/jedi_acquire_bkg.j
  src/Applications/GEOSdas_App/jedi/etc/jedi_acquire_ioda.j
  src/Applications/GEOSdas_App/jedi/etc/jedi_acquire_vbc.j
  src/Applications/GEOSdas_App/jedi/etc/jedi_run_var.j
  src/Applications/GEOSdas_App/jedi/etc/mkiau.rc.tenv
  src/Applications/GEOSdas_App/jedi/etc/obsop_name_map.yaml
  src/Applications/GEOSdas_App/jedi/etc/ut_jedi.j
  src/Applications/GEOSdas_App/jedi/geos2jedi.csh
  src/Applications/GEOSdas_App/jedi/jedi_driver.csh
  src/Applications/GEOSdas_App/jedi/jedi_gsi2ioda.csh
  src/Applications/GEOSdas_App/jedi/jedi_mkiau.csh
  src/Applications/GEOSdas_App/jedi/jedi_post.csh
  src/Applications/GEOSdas_App/jedi/jedi_run.csh
  src/Applications/GEOSdas_App/jedi/jedi_set.csh
  src/Applications/GEOSdas_App/jedi/jedi_swellset.csh
  src/Applications/GEOSdas_App/jedi/jedi_upd4geos.csh
  src/Applications/GEOSdas_App/jedi/setup_aanajedi.pl
  src/Applications/GEOSdas_App/testsuites/j3dfgat.input
  src/Applications/GEOSdas_App/testsuites/j4drpy.input
  src/Applications/GEOSdas_App/write_FVDAS_Run_Config.pl
Labels: 0 diff

#347 Add option for setting 'gross check' value to init_coeffs.f90
  src/Applications/NCEP_Etc/NCEP_bias/init_coeffs.f90
Labels: 0 diff

#356 Var 4d no longer writes out inc; inc generated offline
  src/Applications/GEOSdas_App/jedi/etc/CMakeLists.txt
  src/Applications/GEOSdas_App/jedi/etc/JEDIanaConfig.csh
  src/Applications/GEOSdas_App/jedi/etc/convertana_geos.yaml
  src/Applications/GEOSdas_App/jedi/etc/diffstates_geos.yaml
  src/Applications/GEOSdas_App/jedi/etc/geos_hyb4denvar.yaml
  src/Applications/GEOSdas_App/jedi/jedi_run.csh
  src/Applications/GEOSdas_App/jedi/jedi_set.csh
  src/Applications/GEOSdas_App/jedi/setup_aanajedi.pl
Labels: enhancement, 0 diff

#358 cover for inconsistency in jedi
  src/Applications/GEOSdas_App/jedi/etc/JEDIanaConfig.csh
  src/Applications/GEOSdas_App/jedi/jedi_run.csh
  src/Applications/GEOSdas_App/jedi/setup_aanajedi.pl
Labels: 0 diff trivial

#360 Feature/rtodling/rev 4dsettings1
  src/Applications/GEOSdas_App/GEOSdas.csm
  src/Applications/GEOSdas_App/gen_silo_arc.pl
  src/Applications/GEOSdas_App/jedi/etc/CMakeLists.txt
  src/Applications/GEOSdas_App/jedi/etc/geos_hyb4dcenvar.yaml
  src/Applications/GEOSdas_App/jedi/jedi_mkiau.csh
  src/Applications/GEOSdas_App/jedi/jedi_set.csh
  src/Applications/GEOSdas_App/jedi/jedi_upd4geos.csh
  src/Applications/GEOSdas_App/jedi/setup_aanajedi.pl
Labels: 0 diff

#327 update setup procedures for LADAS
  components.yaml
  src/Applications/GEOSdas_App/AGCMrc.pm
  src/Applications/GEOSdas_App/GEOSdas.csm
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/gen_silo_arc.pl
  src/Applications/GEOSdas_App/testsuites/x3dvar_ladas.input
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmens_arch.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/AGCM.rc.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/AtmEnsConfig.csh
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/HISTAENS.rc.tmpl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/atmens_storage.arc
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/get_atmens_rst.pl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/setup_atmens.pl
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/update_ens.csh
Labels: enhancement, 0 diff

#367 Some generalization of number of vertical levels in analysis
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/jedi/etc/geos_3dfgat.yaml
  src/Applications/GEOSdas_App/jedi/etc/geos_3dvar.yaml
  src/Applications/GEOSdas_App/jedi/etc/geos_hyb3dcenvar.yaml
  src/Applications/GEOSdas_App/jedi/etc/geos_hyb4dcenvar.yaml
  src/Applications/GEOSdas_App/jedi/etc/geos_hyb4denvar.yaml
  src/Applications/GEOSdas_App/jedi/setup_aanajedi.pl
Labels: 0 diff structural

#364 update 'twindow' resource files to remove restriction on GOES-19
  src/Applications/NCEP_Paqc/ChangeLog
  src/Applications/NCEP_Paqc/modify_bufr/twindow.rc
  src/Applications/NCEP_Paqc/modify_bufr/twindow_m2.rc
Labels: 0 diff

#369 Minor changes for JEDI settings and revise OMPS-LP for FP
  components.yaml
  src/Applications/GEOSdas_App/fvsetup
  src/Applications/GEOSdas_App/jedi/etc/JEDIanaConfig.csh
  src/Applications/GEOSdas_App/jedi/etc/convertana_geos.yaml
  src/Applications/GEOSdas_App/jedi/etc/convertinc_geos.yaml
  src/Applications/GEOSdas_App/jedi/etc/diffstates_geos.yaml
  src/Applications/GEOSdas_App/jedi/etc/geos_3dfgat.yaml
  src/Applications/GEOSdas_App/jedi/etc/geos_3dvar.yaml
  src/Applications/GEOSdas_App/jedi/etc/mkiau.rc.tenv
  src/Applications/GEOSdas_App/jedi/jedi_set.csh
  src/Applications/GEOSdas_App/jedi/setup_aanajedi.pl
  src/Applications/GEOSdas_App/testsuites/prePP.input
Labels: 0 diff

#371 Fix for a couple of FP-required output fields
  components.yaml
  src/Applications/GEOSdas_App/jedi/setup_aanajedi.pl
Labels: 0 diff

#374 Fix for incorrect handling of AOD in fcst mode
  components.yaml
  src/Applications/GEOSdas_App/GEOSdas.csm
  src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/gcm_ensset_rc.csh
Labels: 0 diff, bug fix

#376 AMSUA MetopC 4-6 off; revise OMI source
  components.yaml
  src/Applications/GEOSdas_App/testsuites/prePP.input
Labels: Non 0-diff
